### PR TITLE
Tweak and addition

### PR DESCRIPTION
**Pull request by timon1988**
Hi Michiel,

Please check my revisions. I noticed a whole lot inline functions on many of my XSD's, thought it was a shame to transfer all these duplicate codelines to users of the form.

Also, with a pre-filled form when using xsd+xml2html, the add buttons were still available when maxOccurs was already reached. Made a fix for this.

Sorry about the whitespace changes, it seems there were some inconsistencies in the code.

Love this work!
Timon

### CODE REVIEW

**Comment by MichielCM** [comment]
Hi Timon,

Great work! Thanks for sharing your input.

Using JS global functions instead of inline ones makes a lot of sense. Also too bad that there was a maxOccurs error, thanks for fixing it.

It looks like you worked on the latest version, right? Not the 1.0 release version. I am currently working on properly implementing namespace support, I hope to add that in a few weeks. Are you ok with it if I add your suggestions to that version instead of accepting your merge request? Else I'll have a lot of versioning conflicts, since my current codebase has changed quite a bit from the published one...

Best regards,
Michiel

**Comment by timon1988** [comment]
Hi Michiel,

I cloned right into the repo, so that'll be the latest version indeed. I'm
not sure if it's possible, but would it be easier for you if I'd re-request
a pull based on the 1.0 tag? Probably not much work for me to implement the
new code on that one as well.
If not possible, do what seems best to you!

I'll be watching your git for updates :)

Regards,
Timon

**Comment by MichielCM** [comment]
Hi Timon,

Just a heads-up: I committed the new namespace-supported version. It includes your maxOccurs bugfix. I'll do some testing and include your global JS idea. If all works well, I'll release it as v2.0.

Best regards,
Michiel

**Comment by timon1988** [comment]
Hi Michiel,

I noticed! And I see you got the job done in a whole lot less code. Nice
refactoring!

It was my first try at xslt, seems I've got a lot to learn there :)

Regards,
Timon

**Comment by MichielCM** [comment]
This is my first attempt at XSLT in ten years, so I'm sure it can be refactored a whole lot more still... ;)

It's very well suited to this sort of task, but XSLT is horrendous to code in... :')

**Comment by MichielCM** [comment]
A final heads up. I've released version 2 with namespace support and your bugfix, mainly. Thanks again for pointing it out to me!

(I'm closing the pull request.)

**Comment by timon1988** [comment]
Hi Michiel,

Thanks for the update with namespaces and such. I noticed another issue (at
least I think it is).
You use input[type=*], select and textareas for HTML input. But when
clicking the add button, only the input and select fields are enabled (by
removing any disabled attributes), so textareas don't become active when
adding new fields.

Want me to send a PR for it? It's lines
xsd2html.xsl:159 and xsd+xml2html.xsl:167


Regards,
Timon

**Comment by timon1988** [comment]
And add the reference in the JS clickRadioInput function,
xsd2html.xsl:188 and xsd+xml2html.xsl:196

**Comment by MichielCM** [comment]
Hi Timon,

That's a good catch. It's indeed an oversight on my part. A pull request would be great!

Thanks,
Michiel

**Pull request closed without merging**
